---
name: Changed files
description: Get a list of changed files in a directory
inputs:
  folder:
    description: Folder to check for changes
    required: true
    default: .
outputs:
  files:
    description: List of changed files
    value: ${{ steps.changed-files.outputs.all_changed_files }}
runs:
  using: composite
  steps:
    - uses: tj-actions/changed-files@v41
      id: changed-files
      with:
        path: ${{ inputs.folder }}
        dir_names: 'true'
        dir_names_max_depth: 1
        json: true
        quotepath: false
        escape_json: false
