name: 'Run Terraform Apply'
description: 'Run Terraform Apply'
inputs:
  cloud: 
    description: 'Cloud to run the apply on'
    required: true
    default: 'AWS'
  matrix:
    description: 'folders to run the apply on'
    required: true
    default: 'default'
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: ../clone
    
    - name: AWS Login
      if: ${{ inputs.cloud == 'AWS' }}
      uses: ../aws

    - name: Terragrunt Apply
      uses: gruntwork-io/terragrunt-action@v2
      with:
        tf_version: ${{ env.tf_version }}
        tg_version: ${{ env.tg_version }}
        tg_dir: ${{ inputs.matrix }}
        tg_command: 'run-all apply'