---
name: Azure Login
description: Login to Azure using oidc
inputs:
  client-id:
    description: Azure client ID
    required: true
  tenant-id:
    description: Azure tenant ID
    required: true
  subscription-id:
    description: Azure subscription ID
    required: true

runs:
  using: composite
  steps:
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
