---
name: Git Checkout
description: Git clone repository
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure git
      shell: bash
      run: git config --global --add safe.directory /__w/${{ github.repository }}/${{ github.repository }}
