---
name: Decrypt sops secret
description: Decrypt sops secret
inputs:
  file:
    description: sops file to decrypt
    required: true
    default: secrets.sops.hcl
runs:
  using: composite
  steps:
    - name: Sops Binary Installer
      uses: mdgreenwald/mozilla-sops-action@v1.6.0

    - name: Decrypt sops
      shell: bash
      run: |
        sops --config <(echo '') -d ${{ inputs.file }}.enc  > ${{ inputs.file }}
